############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Pricing"
url = "pricing/"
weight = 3

[[main]]
name = "Blog"
url = "/blog"

# footer menu
[[footer]]
name = "Terms of Use"
url = "tos/"
weight = 1

[[footer]]
name = "Disclaimer"
url = "disclaimer/"
weight = 2

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3
