baseURL = "https://guffett.io/"
languageCode = "en-us"
title = "Guffett"
theme = "Agnes"

[params]
	dateFormat = "2023" 
	authorName = "Guffett Technology Inc."
	google_analytics_id = "GA-"
	
[menu]
		
		
[params.content]
	LeadTitle = "Guffett Stock Analyzer"
	LeadDescription = "Discover the Future of Stock Market Analysis with Guffett.io. Our platform uniquely combines the power of ChatGPT and advanced AI to analyze stock news and social media posts, offering unparalleled insights into stock market trends. With Guffett.io, you're not just reading the market sentiment; you're understanding its impact on your investments."
	ButtonCaption = "Get Early Access"
	ButtonURL="https://app.guffett.io"

################### Feature Columns (do not exceed 4) ####################

[[params.feature]]
	FeatureTitle = "How Guffett.io Works"
	FeatureDescription = "At Guffett.io, our process begins with comprehensive data collection, where we gather the latest stock news and social media posts. This information is then intricately analyzed by ChatGPT, identifying key market sentiments and trends. The insights are fed into our sophisticated trading algorithms, each trained on historical data, enabling them to predict future market movements with remarkable accuracy."
	FeatureImage = "images/feature-1.png"
	
[[params.feature]]
	FeatureTitle = "Advanced Sentiment Analysis"
	FeatureDescription = "Understanding market sentiment is just the tip of the iceberg. At Guffett.io, we delve deeper to gauge the actual impact of these sentiments. Our platform doesn't just recognize positive or negative tones; it understands the historical impact of similar sentiments on specific stocks, offering a nuanced and far more accurate market prediction."
	FeatureImage = "images/feature-2.png"

[[params.feature]]
	FeatureTitle = "Our Trading Algorithms"
	FeatureDescription = "Guffett.io's strength lies in its 50+ finely-tuned trading algorithms. Each algorithm is a product of extensive training on historical market data, news, and social media posts. This rigorous training ensures that our algorithms don't just predict market trends – they understand them, offering you a robust tool for your investment decisions."
	FeatureImage = "images/feature-3.png"
	
[[params.feature]]
	FeatureTitle = "Why Choose Guffett.io?"
	FeatureDescription = "Our users enjoy a competitive edge in the stock market, thanks to Guffett.io's advanced AI analysis and comprehensive data interpretation. Experience swift, accurate, and deep market insights that translate into informed investment decisions. Hear from our satisfied clients about how Guffett.io has transformed their trading experience."
	FeatureImage = "images/feature-4.png"
	
################### Pricing Columns (do not exceed 3) ####################

[[params.pricing]]
	PricingTitle = "Starter"
	PricingRate = "20"	
	ButtonCaption = "Get Early Access"
	ButtonURL="https://app.guffett.io"
	[[params.pricing.Features]]
		Description = "Get Daily Stock Prediction of 20+ stocks"
